gui:
  theme:
    activeBorderColor:
      - green
      - bold
git:
  pagers:
    - pager: delta --dark --paging=never
    - pager: ydiff -p cat -s --wrap --width={{columnWidth}}
      colorArg: never
    - externalDiffCommand: difft --color=always
    - {} # default, no pager used
