gui:
  theme:
    activeBorderColor:
      - green
      - bold
git:
  diffRenderers:
    - command: delta --dark --paging=never
    - command: ydiff -p cat -s --wrap --width={{columnWidth}}
      colorArg: never
    - command: difft --color=always
      type: extDiff
    - type: rawGit
