#!/usr/bin/sh
selection=$( \
	echo "Lock|Logout|Suspend|Hibernate|Reboot|Shutdown" |  rofi -sep '|'  \
	rofi -dmenu -i -p 'Option');
echo $selection;

sleep .2

case $selection in
	Lock)
        i3lock -c 000000 -f -i ~/.config/pictures/locked.jpg
		;;
	Logout)
        i3-msg exit
		;;
	Suspend)
        systemctl suspend
		;;
	Hibernate)
        systemctl hibernate
		;;
	Reboot)
        systemctl reboot
		;;
	Shutdown)
        systemctl poweroff -i
		;;
esac

