#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # select name with fzf among provided directories
    selected=$(find ~/projects/ ~/dotfiles/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# cleanup name 
SNAME=$(basename "$selected" | tr . _)

# name session and window
tmux new-session -s $SNAME -n sources -d

# create new named window
tmux new-window -t $SNAME -n term -d

# select window and split
tmux select-window -t $SNAME:term 
# tmux split-window -h
# cmd
# tmux send-keys -t $SNAME:term "git status" Enter

# select window
tmux select-window -t $SNAME:sources
# vi
tmux send-keys -t $SNAME:sources "vi " Enter


tmux -u attach -t $SNAME


